spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jww?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 19970907
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        enable_lazy_load_no_trans: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
debug: true
kira:
  uploadPath: /Users/kira/Desktop/软工/info-mgr/upload/